#!/bin/bash

#$1 = prefix fastq
#$2 = index database path
#$3 CPU
#$4 output/name
snap-aligner paired $2 $(echo $1)_R1_001.fastq $(echo $1)_R2_001.fastq -t $3 -hp -d 8 -D 7 -om 7 -mrl 90 -s 1 1000 -o $(echo $4)_virus.bam

# setting max distance is -d (8)  -om for output multiple ( one reads can be mapped at multiple location  -> more than one virus )  -s lenth between the 2 reads

samtools view -F4 $(echo $4)_virus.bam | cut -f1,3,9 | sort | uniq > $(echo $4)_virus.reads  # .reads  reads:ID \t genome:ID \t len (+-)

samtools sort $(echo $4)_virus.bam -@ $3 -o $(echo $4)_virus.sorted.bam                      # -@ for cpu 

bedtools genomecov -ibam  $(echo $4)_virus.sorted.bam -bga >  $(echo $4)_temp.bga            # coverage file type "bga"

cat $(echo $4)_virus.reads | cut -f 2 | sort | uniq > $(echo $4)_covered_genome.txt          # list of all uniqe virus-match

for i in $(cat $(echo $4)_covered_genome.txt ); do sed -i s/$i/$i"@"$(grep -c $i $(echo $4)_virus.reads)/ $(echo $4)_temp.bga ; done  # for each matched virus, in the bag file the name/id is replace by the same followed by @nbOfRead (nbOfRead = number of reads in sample_virus.reads file (computed with grep -c))
# !!! if there is an error in the sed command, it's pobably beacause of the name/id of the virus in the fasta use to generate the database. It can be checked and modified in the "Gemome" file from the index. -> get rid of special character like "/" 
grep "@" $(echo $4)_temp.bga > $(echo $4).bga

rm $(echo $4)_temp.bga

exit 0

